### PR TITLE
Catch up fork with origin

### PR DESCRIPTION
**Pull request by jfo84**
This PR catches up fake-s3 to its origin branch. We needed to do this because the 2.3 AWS SDK and this fork were not meshing on multi-part uploads. A local JSON import that was larger than 5 MB was throwing odd errors. I was pretty sure this was the culprit after I found this [commit](https://github.com/jubos/fake-s3/commit/40348971b642e92a92e89c4846201acfd7cccca3).

This library now offers most everything that was added to the fork. The `content-disposition` metadata and our specific set of CORS headers were the big differences between our fork and origin.

We will need to update some of our private code by changing our handling of some AWS exceptions to `NoSuchKey` from `NotFound`. According to treverrowe in this [issue](https://github.com/aws/aws-sdk-core-ruby/issues/175), `NoSuchKey` is just a more distinct `NotFound` error that the new `aws-sdk` dependency now raises. We would push this to production by pushing this and the exception handling simultaneously.

We got a clean test run on circle. The id is `34717`; I don't want to link it directly.

You're prime @fgarces! I assume you will want to take a look as well, @jturkel

### CODE REVIEW

**Comment by fgarces** [comment]
@jfo84 can you tell me which classes you modified?

**Comment by jfo84** [comment]
`lib/fakes3/file_store.rb` in the `create_metadata` method. Before the lib wasn't passing any metadata so we added it, but origin now has all metadata except the `content-disposition` stuff

`lib/fakes3/s3_object.rb` for the getter for the above

`lib/fakes3/server.rb` the difference from origin is the `apply_cors_headers` method, which they are now doing but not in exactly the same way. Line 68 is their headers but everything else is ours

That should be it

**Comment by jfo84** [comment]
`assert_equal(response.headers[:access_control_allow_origin],"http://localhost:3535")` from the `post_test.rb` file is also ours

**Comment by fgarces** [comment]
looks good to me :shipit:

**Pull request merged**
